equake <- datasets::quakes
head(equake,10)
tail(equake,10)
equake[,c(3,4)]
df<-equake[,-5]
summary(equake[,2])
equake$depth
summary(equake$depth)
summary(equake)
plot(equake$depth)
plot(equake$depth,equake$mag,type="p")
plot(equake)
plot(equake$depth,type="l")
plot(equake$depth,xlab='index',ylab='depth',main='Eepth of Earthquake',col='blue')
barplot(equake$stations,main='Earthquake Station',ylab='Stations',col='red',horiz=F,axes=T)
hist(equake$stations)
hist(equake$stations,main='Earthquake Stations',xlab='Stations',col='blue')
boxplot(equake$long,main='Longitude')
boxplot(equake[,1:5],main='Multiple')
par(mfrow=c(3,4),mar=c(2,5,2,1),las=0,bty='o')
plot(equake$mag)
plot(equake$mag,equake$stations)
plot(equake$mag, type="l")
barplot(equake$mag,main='Earthquake Magnitude',ylab='Magnitude',col='green',horiz=FALSE)
hist(equake$lat)
boxplot(equake$lat)
boxplot(equake[,1:3],main='Multiple Box Plots')
sd(equake$depth,na.rm=TRUE)
var(equake$depth,na.rm=TRUE)
skewness(equake$depth)
kurtosis(equake$depth)
